name: gtfs_env_311
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - shapely
  - utm
    #"numpy>=1.24.2",
  - numpy
  - pendulum<3
  - branca
  - plotly
  - jenkspy
  - folium
  - jupyter
  - pip
  - pip:
      - unicode

